# Generated by Django 5.1.1 on 2024-12-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='index',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
